apiVersion: apps/v1
kind: Deployment
# This is a simple example of a Deployment configuration file.  
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec: 
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
  replicas: 3
  selector:
    matchLabels:
      env: demo