apiVersion: v1                                          # API version for core Kubernetes resources
kind: Pod                                               # Defines this object as a Pod
metadata:
  name: httpget                                         # Name of the Pod
  labels:
    test: liveness                                      # Label used to identify or filter this Pod

spec:
  containers:                                           # List of containers that will run inside this Pod
  - name: liveness                                      # Name of the container
    image: registry.k8s.io/e2e-test-images/agnhost:2.40 # Container image used (agnhost includes test utilities like HTTP server)
    args:
    - liveness                                          # Run the "liveness" subcommand of agnhost (starts an HTTP server for probing)
    livenessProbe:                                      # Defines a liveness probe for container health checks
      httpGet:                                          # Probe type: send HTTP GET requests to the container
        path: /healthz                                  # URL path to check on the container
        port: 8080                                      # Port number where the HTTP server is listening
      initialDelaySeconds: 5                            # Wait 5 seconds after the container starts before the first probe
      periodSeconds: 5                                  # Run the liveness check every 5 seconds

# liveness probe will restart the pod if the probe fails
# in liveness probe, if the probe fails, the pod will be restarted