apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-new
  name: nginx-new
spec:
  containers:
  - image: nginx
    name: nginx-new
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:  # Node selector to ensure the pod is scheduled on nodes without GPU
    gpu: "false" # This node selector ensures the pod is scheduled on nodes without GPU
status: {}
