apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: myapp-pod
spec:
  containers:             # list of main containers
  - name: app-container   # Main application container
    image: busybox:1.28 # Using a lightweight image, runs a simple shell comm and then exits
    env:                # environment variables for the app container
    - name: firstname
      valueFrom:
        configMapKeyRef:
          name: app-config       # name of the ConfigMap
          key: FIRST_NAME           # key in the ConfigMap to use
    command: ["sh", "-c", "echo Hello from the app container; sleep 3600"]   # command container runs

