# This yaml file creates a Secret that is associated with the service account 'sa-dj'.
apiVersion: v1
kind: Secret
metadata:
  name: dj-secret  # Name of the secret
  annotations:
    kubernetes.io/service-account.name: sa-dj  # Associate this secret with the service account 'sa-dj'
type: kubernetes.io/service-account-token   # Type of secret for service account token
    