# preferredDuringSchedulingIgnoredDuringExecution is used to specify preferred scheduling rules for pods based on node labels.
# these rules are not mandatory, but the scheduler will try to place the pod on nodes that match these preferences if possible.
# this is useful for optimizing resource usage and performance by placing pods on nodes that have specific characteristics.
# Existing pods wil not be affected by these changes, only new pods will be scheduled based on these preferences.
# if no nodes match the preferred rules, the pod will still be scheduled on any available node.
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis-new
spec:
  containers:
  - image: redis
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:     # Node affinity rules for scheduling, specifying which nodes the pod can run on
      preferredDuringSchedulingIgnoredDuringExecution:  # Preferred node affinity rules, will try to schedule on these nodes if possible
        - weight: 100  # Weight of the preference, higher means more preferred
          preference:  # Preference for node labels
            matchExpressions:  # Match expressions for node labels
            - key: disktype    # Key of the label to match
              operator: In   # many operators can be used, such as In, NotIn, Exists, DoesNotExist, Gt, Lt
              values:
              - hhd  # Value of the label to match