# This is a sample YAML file for pod configuration

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    env: demo
    type: frontend
spec:
  containers:
  - name: nginx-container
    image: nginx123
    ports:
    - containerPort: 80
