apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: myapp-pod
spec:
  containers:             # list of main containers
  - name: app-container   # Main application container
    image: busybox:1.28 # Using a lightweight image, runs a simple shell comm and then exits
    command: ["sh", "-c", "echo Hello from the app container; sleep 3600"]   # command container runs
    env:
      - name: FIRST_NAME  # Environment variable for the app container
        value: "Delawar"  # value for the environment variable
  initContainers:         # list of init containers (runs before main containers)
  - name: init-myservice  # name of the init container
    image: busybox:1.28
    command: ["sh", "-c"]
    args: ["until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice to be up; sleep 2; done"]
                          # keeps checking if the service is up every 2 seconds before starting the main container
  - name: init-db  # name of another init container
    image: busybox:1.28
    command: ["sh", "-c"]
    args: ["until nslookup mydb.default.svc.cluster.local; do echo waiting for myservice to be up; sleep 2; done"]
  