apiVersion: v1                  # This specifies the API version of the Kubernetes object
kind: Service
metadata:
  name: nginx-svc
  labels:
    env: demo                   # This label will be used to select the pods that this service will route traffic to
spec:
  type: NodePort                # This specifies that the service will be exposed on a port on each node
  ports:
    - port: 80                  # This is the port that the service will expose
      targetPort: 80
      nodePort: 30001            # This is the port on the node that will be exposed
  selector:                      # This tells the service which pods to route traffic to
    env: demo                    # This will select pods with the label env=demo