# This is a sample YAML file for pod configuration

apiVersion: v1    
kind: Pod
metadata:
  name: nginx-pod2      # This is the name of the pod
  labels:              # Labels are key-value pairs that are attached to objects, such as pods, and can be used to select and filter them
    env: demo
    type: frontend
spec:
  containers:          # This is the specification for the containers that will be created in the pod
  - name: nginx-container    # This is the name of the container
    image: nginx          # This is the image that will be used to create the container
    ports:
    - containerPort: 80    # This is the port that the container will expose
